### ISSUE TITLE
Trouble with GUI

### ISSUE THREAD

**Issue by Alibohra** [nawrotlab/larvaworld#2]
<img width="573" alt="Screenshot 2022-09-05 at 12 57 06" src="https://user-images.githubusercontent.com/33547850/188433792-a3119816-3b45-4fae-9856-706a1a022400.png">
Having trouble Launching the GUI.

**Comment by bagjohn** [comment]
Hello and thanks for trying this out!

The code has been updated and the GUI is currently deprecated.

Feel free to try it out and report any issues.
